### ISSUE TITLE
Don't spawn lsof multiple times

### ISSUE THREAD

**Issue by jeff-h** [Fus1onDev/EjectKey#8]
I admit I haven't run the app yet (looks lovely though!) but I think your code will spawn many `lsof` instances?

https://github.com/fus1ondev/EjectKey/blob/549315b138314ff4e7f732d2c0aa6891b9afffa0/EjectKey/Objects/Volume.swift#L130-L132

Probably better to run `lsof` once, without specifying a pid, before the `for` loop, then cycle through the running applications.

**Comment by yk4to** [comment]
Hi Jeff,

Certainly, this is not good for performance.

I found that `lsof` command has `+D` option to output only under a specific directory, so I used that and was able to shorten the code significantly.

Thank you very much for your suggestion!
